project:
  type: website
  output-dir: docs
  render:
    - scripts/index.qmd
    - scripts/bodysizedosing.qmd

website:
  title: "Pharmacoanthropometrics"
  navbar:
    left:
      - text: "Dosing and Body Size"
        href: scripts/bodysizedosing.qmd
