project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - scripts/proof.qmd

website:
  title: "Pharmacoanthropometrics"
  navbar:
    left:
      - text: "Graphical Proof"
        href: scripts/proof.qmd
