---
title: "Dosing and Body Size"
author: "Ryan Crass"
format: html
editor: visual
---


# Set Up

## Packages 

```{r pkgs}
rm(list=ls())
library(nhanesA)
library(tidyverse)
```

#y = x^alpha, can be fitted  (e.g. CL = (WT/70)^alpha)
#x = z^beta, can be fitted for a population (e.g., WT = BSA^beta)
#y = (z^beta)^alpha = z^(beta*alpha)
#Desire for linear relationship (e.g., mg/z) between response variable y and dosing variable z, thus
# 1 = beta*alpha

## NHANES Data

```{r nhanes}
bmx <- nhanes("BMX")
demo <- nhanes("DEMO")

data <- left_join(bmx, demo) %>% 
  filter(!is.na(RIDAGEYR) & !is.na(RIAGENDR) & !is.na(BMXWT) & !is.na(BMXHT))
```

# Define Body Size Metrics

Source: https://pubmed.ncbi.nlm.nih.gov/22711238/

```{r anthropometrics}

anthro <- data %>% 
  select(SEQN, 
         AGEYR = RIDAGEYR, 
         SEX = RIAGENDR, 
         WTKG = BMXWT,
         HTCM = BMXHT, 
         BMIKGM2 = BMXBMI) %>% 
  mutate(BSAMOSM2 = signif(sqrt(WTKG*HTCM/3600),3), 
         BSADUBM2 = signif(0.007184 * (WTKG^0.425) * (HTCM^0.725),digits=3),
         IBWKG = ifelse(SEX == "Male", 
                      signif(50 + 2.3*((HTCM/2.54)-60),3),
                      signif(45.5 + 2.3*((HTCM/2.54)-60),3)), 
         IBWKG = signif(IBWKG, digits=3),
         AIBWKG = signif(IBWKG + 0.4*(WTKG-IBWKG), digits=3),
         FFWKG = ifelse(SEX == "Male", 
                        signif((0.285 *  WTKG) + (12.1 * (HTCM/100)^2),3),
                        signif((0.287 *  WTKG) + (9.74 * (HTCM/100)^2),3)),
         LBWKG = ifelse(SEX == "Male", 
                        signif((9270 *  WTKG) / (6680 + 216 * BMIKGM2),3),
                        signif((9270 *  WTKG) / (8780 + 244 * BMIKGM2),3))
         )


anthro_adult <- anthro %>% 
  filter(AGEYR>18)
```

```{r weight-metric-fit}
params <- c("HTCM", "BMIKGM2", "BSAMOSM2", "BSADUBM2", "IBWKG", "AIBWKG", "FFWKG", "LBWKG")
ll_fit <- data.frame("PARAM" = params, SLOPE = NA_real_)
for(par in params){
  coef <- lm(log(anthro_adult[["WTKG"]]) ~ log(anthro_adult[[par]]))$coefficients[[2]]
  ll_fit$SLOPE[ll_fit$PARAM==par] = coef
} 

fit <- ll_fit %>% 
  bind_rows(data.frame("PARAM" = "WTKG", SLOPE = 1))
```

```{r summary-fit}
summary_fit <- fit %>% 
  mutate(Y01 = signif(SLOPE*0.1, digits=3),
         Y03 = signif(SLOPE*0.3, digits=3),
         Y05 = signif(SLOPE*0.5, digits=3),
         Y07 = signif(SLOPE*0.7, digits=3),
         Y09 = signif(SLOPE*0.9, digits=3),
         Y10 = signif(SLOPE, digits=3), 
         Y13 = signif(SLOPE*1.3, digits=3),
         Y15 = signif(SLOPE*1.5, digits=3), 
         Y17 = signif(SLOPE*1.7, digits=3),
         Y20 = signif(SLOPE*2, digits=3)) 

summary_fit_long <- summary_fit %>% 
  pivot_longer(Y01:Y20, names_to = "WTEXP", values_to = "XWTEXP") %>% 
  mutate(WTEXP = as.numeric(gsub("[^0-9]+", "", WTEXP))/10)
```


```{r plot}
ggplot(aes(x = WTEXP, y = XWTEXP, col = PARAM), data = summary_fit_long) + 
  geom_point() +
  geom_abline(aes(intercept = 0, slope = SLOPE, col = PARAM), data = fit) + 
  geom_hline(yintercept = 1) + 
  geom_hline(yintercept = c(0.8, 1.2), linetype = "dashed") + 
  scale_x_continuous(limits = c(NA, 2), breaks = c(0, 0.5, 0.75, 1, 1.25, 1.5, 2)) + 
  scale_y_continuous(limits = c(NA, 2), breaks = c(0, 0.5, 1, 1.5, 2)) + 
  theme_bw() + 
  theme(panel.grid.major.y = element_blank(), 
        panel.grid.minor.y = element_blank())
```         